### ISSUE TITLE
Embedded binaries in blpapi wheels since 3.16.3

### ISSUE THREAD

**Issue by nsergey82** [conda-forge/blpapi-feedstock#16]
1. Per https://www.bloomberg.com/professional/support/api-library/ from version 3.16.3 
Bloomberg ships the C++ binaries within the wheels. Just doing the good old
`python -m pip install --index-url=https://bcms.bloomberg.com/pip/simple/ blpapi` should be sufficient for most platforms.
Python3.9 is not yet supported, probably in the next version.

2. https://bloomberg.bintray.com is EOL, 
BCMS (Bloomberg Content Management System) is the new public file host for the libraries: https://bcms.bloomberg.com/BLPAPI-Generic/ and https://bcms.bloomberg.com/pip/simple/blpapi/

**Comment by matthewgilbert** [comment]
Great thanks for pointing this out. Would you be able to submit a PR to update the endpoints? There's a discussion of the process at https://github.com/conda-forge/blpapi-feedstock#updating-blpapi-feedstock. For this I think we would need to

1. Update the url section `recipe/meta.yaml`
2. Bump the build number in `recipe/meta.yaml`

**Comment by matthewgilbert** [comment]
This has been resolved in https://github.com/conda-forge/blpapi-feedstock/pull/17
