### ISSUE TITLE
No win py39 cpython builds for 3.18.3+

### ISSUE THREAD

**Issue by lguo52** [conda-forge/blpapi-feedstock#37]
### Comment:

Hello, I noticed that there are no windows py39 cpython builds for versions 3.18.3 and 3.19.1.  Would someone be able to build and publish those? Thank you!

**Comment by reggied** [comment]
Hi @lguo52 , when I look at the [conda-forge downloads page](https://anaconda.org/conda-forge/blpapi/files), I'm seeing https://anaconda.org/conda-forge/blpapi/3.18.3/download/win-64/blpapi-3.18.3-py39_blpapicpp3.18.4.1_1.tar.bz2 and https://anaconda.org/conda-forge/blpapi/3.19.1/download/win-64/blpapi-3.19.1-py39_blpapicpp3.19.1.1_0.tar.bz2 . Are they not working for you or are you looking somewhere else?

**Comment by lguo52** [comment]
Those are pypy builds:
```
blpapi 3.18.3 py39_blpapicpp3.18.4.1_1
--------------------------------------
file name   : blpapi-3.18.3-py39_blpapicpp3.18.4.1_1.tar.bz2
name        : blpapi
version     : 3.18.3
build string: py39_blpapicpp3.18.4.1_1
build number: 1
channel     : https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge/win-64
size        : 7.4 MB
arch        : None
constrains  : ()
license     : Copyright 2012. Bloomberg Finance L.P.
md5         : 353e8769ffa92a1c72d8f538f994a0ad
platform    : None
sha256      : c0f8ea52c3a84e69e46f1b6d814170a979f1db24cf70994fc355355c6d0a47fb
subdir      : win-64
timestamp   : 1667676878530
url         : https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge/win-64/blpapi-3.18.3-py39_blpapicpp3.18.4.1_1.tar.bz2
dependencies:
    pypy3.9 >=7.3.9
    python >=3.9,<3.10.0a0
    python_abi 3.9 *_pypy39_pp73
    ucrt >=10.0.20348.0
    vc >=14.2,<15
    vs2015_runtime >=14.29.30139
```
We need to use the cpython builds instead, like for 3.17.1:
```
blpapi 3.17.1 py39_blpapicpp3.16.1.1_1
--------------------------------------
file name   : blpapi-3.17.1-py39_blpapicpp3.16.1.1_1.tar.bz2
name        : blpapi
version     : 3.17.1
build string: py39_blpapicpp3.16.1.1_1
build number: 1
channel     : https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge/win-64
size        : 6.2 MB
arch        : None
constrains  : ()
license     : Copyright 2012. Bloomberg Finance L.P.
md5         : 1dabee7da56090ec37ba7c47c1ebb97b
platform    : None
sha256      : 7675fe224aa1d56ab2cc0170bdc5294d81389489bee25e7745e91103a8184336
subdir      : win-64
timestamp   : 1655703104545
url         : https://artprod.dev.bloomberg.com/artifactory/api/conda/conda-forge/win-64/blpapi-3.17.1-py39_blpapicpp3.16.1.1_1.tar.bz2
dependencies:
    python >=3.9,<3.10.0a0
    python_abi 3.9.* *_cp39
    vc >=14.1,<15
    vs2015_runtime >=14.16.27033
```

Note the python_abi buildstring `pypy39_pp73` vs `cp39`

**Comment by SylvainCorlay** [comment]
@lguo52 the issue is that the build string for PyPy and cpython builds are the same.

By overriding the build string without including `{{ PKG_HASH }}` in it, this allowed builds for different Python flavors to have exactly the same artifact name. This has been the case for nearly four years apparently. Whichever build completed first is the one that would be on anaconda.org.

A simple fix would be to include `_h{{ PKG_HASH }}` in the build string, but I would be tempted to completely remove all customization of the build string in the recipe. Any specific reason for the build string to be customized at all @reggied @matthewgilbert?
