### ISSUE TITLE
Bloomberg library link changed

### ISSUE THREAD

**Issue by nsergey82** [conda-forge/blpapi-feedstock#45]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Note: the Bloomberg links are now different, BCMS is deprecated.
Consider updating from https://www.bloomberg.com/professional/support/api-library/
With that said, python blpapi is now shipped in wheels which already contain a C++ binary. 
So the script in this repo is not strictly needed. One can just:
`python -m pip install ‑‑index-url=https://blpapi.bloomberg.com/repository/releases/python/simple blpapi`

### Installed packages

```shell
None
```

### Environment info

```shell
None
```

**Comment by adament** [comment]
Thank you, I think this should be fixed with the latest pull request.
